import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  
  const onLoad = () => {
    window.red
  }
  
  
  return (
    <>
      <Head>
        <title>Harmoniq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>

        <div className={styles.center}>
          <h1>Harmoniq</h1>
        </div>

        <div className={styles.grid}>
          <a
            href="/unwrapped"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              Unwrapped <span>-&gt;</span>
            </h2>
            <p>
              Discover your latest unwrapped Spotify stats and share them with friends.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
